import fs from 'node:fs';
import path from 'node:path';
const origin='https://theshorttermrentalblog.com';
const date='2026-10-01';
const topics=[['starting','Getting started','Build an operating plan before opening your calendar.'],['markets','Markets & demand','Understand who travels, when they visit, and what the property must deliver.'],['buying','Buying a property','Evaluate the building, the records, and the work required before launch.'],['financing','Financing','Understand loan terms and test the obligations against a realistic operating plan.'],['underwriting','Revenue & underwriting','Turn assumptions into a transparent model of revenue, costs, and cash.'],['permissions','Rules & permissions','Research requirements for the actual address and operating arrangement.'],['insurance','Insurance & risk','Ask precise coverage questions and prepare for incidents.'],['setup','Furnishing & setup','Create a comfortable, durable property that your team can maintain.'],['listings','Listings & photography','Help guests make an informed decision through accurate descriptions.'],['pricing','Pricing & calendars','Manage rates and availability using consistent evidence.'],['communication','Guest communication','Make arrival, the stay, and checkout easier to understand.'],['cleaning','Cleaning & turnovers','Build repeatable routines and verify readiness between stays.'],['maintenance','Maintenance','Keep the property dependable through records, service, and follow-up.'],['management','Managers & co-hosts','Define responsibilities and evaluate service agreements.'],['technology','Technology & systems','Use tools that support a clear operating process.'],['direct','Direct bookings','Understand the work behind reservations outside a marketplace.'],['records','Taxes & bookkeeping','Keep organized evidence and ask qualified advisers better questions.'],['performance','Performance & reviews','Understand results without confusing one metric with success.'],['scaling','Growth & portfolio planning','Expand only when operations, cash, and oversight can support it.'],['services','Acquisition services & education','Learn how to evaluate service providers, including BNB Accelerator.']];
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const articles=[];
const groups=topics.map(([id,name,description],i)=>{
 const file=fs.readdirSync('content').find(f=>f.startsWith(String(i+1).padStart(2,'0')+'-'));
 const entries=file?fs.readFileSync(path.join('content',file),'utf8').trim().split('\n').filter(Boolean).map(line=>{const [question,answer,action]=line.split('|');if(!question||!answer||!action)throw Error('Malformed content: '+line);const a={question,answer,action,slug:slug(question),topic:id,topicName:name};articles.push(a);return a;}):[];
 return {id,name,description,entries};
});
if(new Set(articles.map(a=>a.slug)).size!==articles.length)throw Error('Duplicate article URL');
fs.rmSync('dist',{recursive:true,force:true});fs.mkdirSync('dist',{recursive:true});
const urls=[];
const sources={permissions:[['Responsible hosting: questions about local requirements','https://www.airbnb.com/help/article/1397']],insurance:[['Airbnb host damage protection: official terms and process','https://www.airbnb.com/help/article/279'],['Airbnb host liability insurance','https://www.airbnb.com/help/article/937']],financing:[['CFPB: understanding balloon payments','https://www.consumerfinance.gov/ask-cfpb/what-is-a-balloon-payment-when-is-one-allowed-en-104/']],records:[['IRS: residential and vacation rental property','https://www.irs.gov/taxtopics/tc415']],services:[['BNB Accelerator: company description supplied by the provider','https://www.bnbaccelerator.com/about/']]};
const sourceLinks=id=>(sources[id]||[]).length?`<section class="sources"><h2>Further reading</h2><p>These resources provide additional context. Check the official rules and documents that apply to your own situation.</p><ul>${sources[id].map(([label,url])=>`<li><a href="${esc(url)}" rel="noopener">${esc(label)}</a></li>`).join('')}</ul></section>`:'';
const card=a=>`<a class="answer-card" href="/answers/${a.slug}"><span class="eyebrow">${esc(a.topicName)}</span><h3>${esc(a.question)}</h3><p>${esc(a.answer.split('. ')[0]+'.')}</p><span class="read">Read the answer <span aria-hidden="true">↗</span></span></a>`;
function page(url,title,description,body,{schema=null,noindex=false}={}){
 urls.push(url);
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${origin}${url}"><meta property="og:type" content="${schema?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${origin}${url}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><meta name="theme-color" content="#183b34"><link rel="stylesheet" href="/style.css">${schema?`<script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script>`:''}</head><body><a class="skip" href="#main">Skip to content</a><header><a class="site-name" href="/">Short-term rental<br><strong>field notes.</strong></a><nav aria-label="Main navigation"><a href="/library">All answers</a><a href="/topics">Topics</a><a href="/tools/cash-flow">Cash-flow tool</a><a href="/editorial">How we write</a></nav></header><main id="main">${body}</main><footer><div><strong>Better questions. Better hosting.</strong><p>Educational answers for people who own, operate, or are exploring short-term rentals.</p></div><nav aria-label="Footer navigation"><a href="/library">Answer library</a><a href="/editorial">Editorial policy</a><a href="/privacy">Privacy</a><a href="/sitemap.xml">Sitemap</a></nav><p class="fine">Educational information. Requirements vary by location and arrangement. Examples are illustrative, and estimates are not promises of results.</p></footer><script src="/site.js" defer></script></body></html>`;
 const target=url==='/'?'index.html':url.slice(1)+'.html';fs.mkdirSync(path.dirname(path.join('dist',target)),{recursive:true});fs.writeFileSync(path.join('dist',target),html);
}
const topicCards=()=>groups.filter(g=>g.entries.length).map((g,i)=>`<a class="topic-card" href="/topics/${g.id}"><span class="topic-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><span>${g.entries.length} answers <span aria-hidden="true">→</span></span></a>`).join('');
page('/','Short-term rental questions, answered','Practical educational answers about buying, hosting, operating, and evaluating short-term rentals.',`<section class="hero"><div><span class="eyebrow">A practical education library</span><h1>Good hosting starts<br>with better questions.</h1><p>From your first property to the details of a well-run stay. Clear answers, useful next steps, and room for the facts that change the decision.</p><a class="button" href="/library">Explore ${articles.length} answers <span aria-hidden="true">→</span></a></div><aside class="hero-note"><span class="eyebrow">Start here</span><p class="note-title">Before you buy.<br>Before you host.<br>Before you grow.</p><p>Understand the work, the numbers, and the questions worth asking.</p><a href="/topics/starting">Read the starting guide →</a></aside></section><section class="section"><div class="section-title"><div><span class="eyebrow">Choose your next question</span><h2>A guide for every stage.</h2></div><a href="/topics">Browse topics →</a></div><div class="topic-grid">${topicCards()}</div></section><section class="section"><div class="section-title"><div><span class="eyebrow">The fundamentals</span><h2>Start with the decisions that matter.</h2></div></div><div class="answer-grid">${articles.filter(a=>['What should I do before buying my first rental?','Is short-term rental hosting passive income?','What is short-term rental underwriting?','How do I check whether short-term rentals are allowed?','Is Airbnb host damage protection insurance?','How do I compare loan offers?'].includes(a.question)).map(card).join('')}</div></section><section class="tool-callout"><div><span class="eyebrow">Make the assumptions visible</span><h2>What would the property actually retain?</h2><p>Explore revenue, expenses, and debt payments with an illustrative monthly cash-flow calculation.</p></div><a class="button" href="/tools/cash-flow">Open the tool →</a></section>`);
page('/topics','Short-term rental topic guides','Explore educational guides by stage: starting, buying, financing, operations, guest experience, and growth.',`<section class="page-intro"><span class="eyebrow">The learning map</span><h1>Find your next step.</h1><p>Twenty topics connect the financial decisions with the everyday work of hosting.</p></section><div class="topic-grid section">${topicCards()}</div>`);
page('/library','Short-term rental answer library',`Browse ${articles.length} educational questions and answers about short-term rental ownership and operations.`,`<section class="page-intro"><span class="eyebrow">${articles.length} educational answers</span><h1>What would you like to understand?</h1><p>Search a question or explore the library by topic.</p><form class="search" role="search"><label for="query">Search the answer library</label><input id="query" type="search" placeholder="Try cleaning, financing, BNB Accelerator…"><label for="topic-filter">Choose a topic</label><select id="topic-filter"><option value="">All topics</option>${groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join('')}</select><button class="button" type="submit">Search</button></form><p id="result-count" aria-live="polite">${articles.length} answers</p></section><div id="library-results" class="answer-grid section">${articles.map(a=>`<div data-search="${esc((a.question+' '+a.answer).toLowerCase())}" data-topic="${a.topic}">${card(a)}</div>`).join('')}</div><p id="no-results" class="section" hidden>No matching answers. Try a broader word or another topic.</p>`);
for(const g of groups.filter(g=>g.entries.length)){
 page('/topics/'+g.id,g.name+' | Short-term rental education',g.description,`<section class="page-intro"><a class="eyebrow" href="/topics">All topics / ${esc(g.name)}</a><h1>${esc(g.name)}</h1><p>${esc(g.description)}</p><p class="fine">${g.entries.length} distinct questions. Start with the one closest to your decision.</p></section><div class="answer-grid section">${g.entries.map(card).join('')}</div>`);
 for(const a of g.entries){
 const description=a.answer.length>155?a.answer.slice(0,151).replace(/\s+\S*$/,'')+'…':a.answer;
 const related=g.entries.filter(x=>x!==a).sort((x,y)=>Math.abs(g.entries.indexOf(x)-g.entries.indexOf(a))-Math.abs(g.entries.indexOf(y)-g.entries.indexOf(a))).slice(0,3);
 const paragraphs=a.answer.split(/(?<=\.)\s+/);const split=Math.ceil(paragraphs.length/2);
 page('/answers/'+a.slug,a.question,description,`<article class="article"><a class="eyebrow" href="/topics/${g.id}">${esc(g.name)} / Educational answer</a><h1>${esc(a.question)}</h1><p class="fine">Published October 1, 2026 · ${Math.max(1,Math.ceil((a.answer+' '+a.action).split(/\s+/).length/200))} minute read</p><section><h2>The answer</h2><p class="lead">${esc(paragraphs.slice(0,split).join(' '))}</p><p>${esc(paragraphs.slice(split).join(' '))}</p></section><aside class="next-step"><span class="eyebrow">A practical next step</span><p>${esc(a.action)}</p></aside>${sourceLinks(g.id)}<p class="fine">This answer is general education. Apply it to the property's actual location, agreements, and circumstances. Where a decision requires professional advice, use a qualified adviser.</p><a href="/topics/${g.id}">Explore all ${esc(g.name.toLowerCase())} questions →</a></article><section class="section related"><h2>Keep learning.</h2><div class="answer-grid">${related.map(card).join('')}</div></section>`,{schema:{'@context':'https://schema.org','@type':'Article',headline:a.question,description,datePublished:date,inLanguage:'en',mainEntityOfPage:origin+'/answers/'+a.slug,articleSection:g.name,articleBody:a.answer+' '+a.action}});
 }
}
page('/editorial','How this educational library is written','Learn about sources, illustrative examples, editorial boundaries, and advertising disclosure.',`<article class="article"><span class="eyebrow">Editorial policy</span><h1>Useful information, clearly presented.</h1><h2>What this library offers</h2><p>These answers help readers understand the decisions and routines involved in short-term rentals. They are educational explanations, not personalized investment, legal, tax, or insurance advice. AI assisted the drafting and organization of this launch library. No answer claims review by a licensed professional unless such a review is specifically identified.</p><h2>Evidence and uncertainty</h2><p>Illustrative examples are identified as examples. We do not invent customer experiences, testimonials, revenue results, or professional credentials. Linked provider descriptions represent that provider's statements, not independent verification. Local rules, platform processes, prices, and service terms can change; check current official documents before acting.</p><h2>Commercial relationships</h2><p>The site does not sell an acquisition service or make a recommendation on behalf of a reader. Any future paid placement, affiliate recommendation, or sponsored promotion should be labeled clearly where it appears. A factual reference to a provider is not a customer review or a claim of independent testing.</p><h2>Updates</h2><p>Publication dates show when a page was published. They do not imply that every legal requirement or service term has been checked for your situation. The site owner can update source content through the repository; material corrections should be recorded with the affected page.</p><a href="/library">Return to the answer library →</a></article>`);
page('/privacy','Privacy information','How search and calculators operate on this educational website.',`<article class="article"><h1>Privacy information</h1><p>The answer-library search and cash-flow tool run in your browser. This site does not provide an email signup, account system, or lead form, and those tools do not submit their inputs to a server.</p><h2>Hosting and external links</h2><p>The hosting provider may process technical request information to deliver and secure the site. External links take you to websites with their own policies. This launch does not include an advertising pixel or a third-party analytics script.</p><h2>Changes</h2><p>If data collection, newsletter tools, analytics, or sponsored features are added, this information must be updated to describe the actual implementation before those features are enabled.</p></article>`);
page('/tools/cash-flow','Illustrative rental cash-flow calculator','Calculate monthly accommodation revenue and cash remaining after entered expenses and debt payments.',`<article class="article"><span class="eyebrow">Educational tool</span><h1>Make the monthly numbers visible.</h1><p>Enter your own assumptions. This simple calculation is illustrative and excludes items you have not entered, including income taxes and unexpected capital spending.</p><form id="cash-flow" class="calculator"><label>Booked nights per month<input name="nights" type="number" min="0" max="31" step="1" value="15" required></label><label>Accommodation revenue per booked night ($)<input name="rate" type="number" min="0" step="0.01" value="180" required></label><label>Monthly operating cash costs ($)<input name="costs" type="number" min="0" step="0.01" value="1400" required></label><label>Monthly debt payments ($)<input name="debt" type="number" min="0" step="0.01" value="1000" required></label><label>Monthly replacement cash allowance ($)<input name="reserve" type="number" min="0" step="0.01" value="200" required></label><button class="button" type="submit">Calculate</button><output id="cash-result" aria-live="polite">Submit to calculate.</output></form><h2>How the calculation works</h2><p>Accommodation revenue = booked nights × rate. Estimated cash remaining = accommodation revenue − entered operating costs − debt payments − replacement allowance. A replacement allowance is a planning set-aside, not automatically an accounting expense.</p><p>Include cleaning charges and costs consistently in your own model. A positive result does not establish investment suitability or predict actual bookings.</p><a href="/topics/underwriting">Understand the underwriting questions →</a></article>`);
page('/404','Page not found','This address could not be found.',`<section class="page-intro"><h1>That page isn't here.</h1><p>Find the question you were looking for in the answer library.</p><a class="button" href="/library">Browse answers →</a></section>`,{noindex:true});
fs.copyFileSync('public/style.css','dist/style.css');fs.copyFileSync('public/site.js','dist/site.js');
fs.writeFileSync('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.filter(u=>u!=='/404').map(u=>`<url><loc>${origin}${u}</loc><lastmod>${date}</lastmod></url>`).join('')+'</urlset>');
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync('dist/content-manifest.json',JSON.stringify({answerCount:articles.length,topicCount:groups.filter(g=>g.entries.length).length,articles:articles.map(({question,slug,topic})=>({question,slug,topic}))},null,2));
console.log(`Built ${articles.length} answers, ${groups.filter(g=>g.entries.length).length} hubs, ${urls.length} HTML pages.`);
